import { defineConfig } from 'tsup'

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      'better-auth': 'src/better-auth/index.ts',
      clerk: 'src/clerk/index.ts',
      workos: 'src/workos/index.ts',
      standalone: 'src/frameworks/standalone/index.ts',
      elysia: 'src/frameworks/elysia/index.ts',
      hono: 'src/frameworks/hono/index.ts',
      express: 'src/frameworks/express/index.ts',
      fastify: 'src/frameworks/fastify/index.ts',
      nestjs: 'src/frameworks/nestjs/index.ts',
      nextjs: 'src/frameworks/nextjs/index.ts',
      'react-router': 'src/frameworks/react-router/index.ts',
      'tanstack-start': 'src/frameworks/tanstack-start/index.ts',
      'solid-start': 'src/frameworks/solid-start/index.ts',
      sveltekit: 'src/frameworks/sveltekit/index.ts',
      astro: 'src/frameworks/astro/index.ts',
      nitro: 'src/frameworks/nitro/index.ts',
      nuxt: 'src/frameworks/nuxt/index.ts',
      'ai/vercel': 'src/ai/vercel/index.ts',
      'ai/better-agent': 'src/ai/better-agent/index.ts',
      'ai/openai': 'src/ai/openai/index.ts',
      'ai/anthropic': 'src/ai/anthropic/index.ts',
      'ai/shared': 'src/ai/shared/index.ts',
      'ai/fetch': 'src/ai/shared/fetch.ts',
      database: 'src/database/index.ts',
      'connectors/http': 'src/connectors/http/index.ts',
      'connectors/cloud': 'src/connectors/cloud/index.ts',
      'connectors/betterstack': 'src/connectors/betterstack/index.ts',
      'connectors/databuddy': 'src/connectors/databuddy/index.ts',
      'connectors/posthog': 'src/connectors/posthog/index.ts',
      'connectors/otlp': 'src/connectors/otlp/index.ts',
      'connectors/sentry': 'src/connectors/sentry/index.ts',
    },
    format: ['cjs', 'esm'],
    dts: false,
    splitting: false,
    sourcemap: false,
    clean: true,
    outDir: 'dist',
    target: 'es2020',
    minify: true,
    treeshake: true,
    external: [
      'elysia',
      'hono',
      'express',
      'fastify',
      'fastify-plugin',
      '@nestjs/common',
      '@nestjs/core',
      '@nestjs/platform-express',
      '@nestjs/platform-fastify',
      '@nestjs/microservices',
      '@nestjs/microservices/microservices-module',
      '@nestjs/websockets',
      '@nestjs/websockets/socket-module',
      'class-transformer',
      'class-validator',
      'next',
      'react-router',
      'rxjs',
      '@tanstack/react-start',
      '@sveltejs/kit',
      'astro',
      'nitropack',
      'nuxt',
      'ai',
      '@better-agent/core',
      '@clerk/backend',
      'better-auth',
      'better-auth/api',
      'better-auth/client',
      '@workos-inc/node',
      'winston',
      'chalk',
      '@sentry/node',
      '@databuddy/sdk',
      '@databuddy/sdk/node',
      '@logtail/node',
      'posthog-node',
      '@opentelemetry/api-logs',
      '@opentelemetry/exporter-logs-otlp-http',
      '@opentelemetry/resources',
      '@opentelemetry/sdk-logs',
      'jiti',
    ],
    noExternal: [],
    esbuildOptions(options) {
      options.define = {
        'require.resolve': 'undefined'
      }
    },
    platform: 'node',
  },
  {
    entry: {
      client: 'src/frameworks/client/index.ts',
      expo: 'src/frameworks/expo/index.ts',
      workers: 'src/frameworks/workers/index.ts',
    },
    format: ['cjs', 'esm'],
    // These public entrypoints already ship manual declaration shims under /types.
    // Skipping the second tsup DTS pass avoids a redundant worker-heavy type build.
    dts: false,
    splitting: false,
    sourcemap: false,
    clean: false,
    outDir: 'dist',
    target: 'es2020',
    minify: true,
    treeshake: true,
    platform: 'browser',
    external: ['expo-network'],
  },
])
