export declare function getMethodColor(method: string): string;
export declare function getStatusColor(statusCode: number): string;
export declare function getArrowForMethod(method: string): string;
export declare function getResponseTimeColor(ms: number): string;
export declare function getColoredLevel(level: string): string;
export declare const colors: {
    reset: string;
    bright: string;
    dim: string;
    underscore: string;
    blink: string;
    reverse: string;
    hidden: string;
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
    bgBlack: string;
    bgRed: string;
    bgGreen: string;
    bgYellow: string;
    bgBlue: string;
    bgMagenta: string;
    bgCyan: string;
    bgWhite: string;
};
