import { type BlypConfig } from './config';
import type { BetterStackSender } from '../types/connectors/betterstack';
import type { PostHogSender } from '../types/connectors/posthog';
import type { SentrySender } from '../types/connectors/sentry';
import type { OTLPRegistry } from '../types/connectors/otlp';
import type { StructuredLog } from '../types/core/structured-log';
import type { BlypLogger, InternalLoggerSource, StructuredLogFactoryOptions } from '../types/core/logger';
export type { BlypLogger } from '../types/core/logger';
export declare const CUSTOM_LEVELS: Record<string, number>;
export declare function getPostHogSender(logger: BlypLogger): PostHogSender;
export declare function getBetterStackSender(logger: BlypLogger): BetterStackSender;
export declare function tryGetPostHogSender(logger: unknown): PostHogSender | null;
export declare function tryGetBetterStackSender(logger: unknown): BetterStackSender | null;
export declare function getSentrySender(logger: BlypLogger): SentrySender;
export declare function getOtlpRegistry(logger: BlypLogger): OTLPRegistry;
export declare function attachLoggerInternals<T extends BlypLogger>(target: T, source: BlypLogger): T;
export declare function createLoggerWithSource(logger: BlypLogger, source: InternalLoggerSource): BlypLogger;
export declare function createStructuredLogForLogger(logger: BlypLogger, groupId: string, options?: StructuredLogFactoryOptions): StructuredLog;
export declare function createBaseLogger(config?: Partial<BlypConfig>): BlypLogger;
export declare const logger: BlypLogger;
