import { normalizeError, normalizeLogValue, serializeLogMessage } from './log-value';
import type { ClientLogBrowserContext, ClientLogEvent, ClientLogLevel, ClientLogPageContext } from '../types/shared/client-log';
export type { ClientConnectorRequest, ClientLogBrowserContext, ClientLogDeviceContext, ClientLogEvent, ClientLogLevel, ClientLogPageContext, ClientLogSessionContext, RemoteDeliveryConfig, RemoteDeliveryDropContext, RemoteDeliveryFailureContext, RemoteDeliveryFailureReason, RemoteDeliveryRetryContext, RemoteDeliverySuccessContext, RemoteDeliveryTransport, } from '../types/shared/client-log';
export declare const DEFAULT_CLIENT_LOG_ENDPOINT = "/inngest";
export declare function createRandomId(): string;
export declare function normalizeClientLogLevel(level: ClientLogLevel | 'warn'): ClientLogLevel;
export { normalizeError, normalizeLogValue, serializeLogMessage };
export declare function normalizeClientPayloadData(message: unknown, args: unknown[]): unknown;
export declare function getBrowserPageContext(): ClientLogPageContext;
export declare function getBrowserContext(): ClientLogBrowserContext;
export declare function getClientSessionId(): string;
export declare function normalizeMetadata(metadata: Record<string, unknown> | (() => Record<string, unknown>) | undefined): Record<string, unknown> | undefined;
export declare function isClientLogEvent(payload: unknown): payload is ClientLogEvent;
export declare function normalizeEndpointPath(path: string | undefined): string;
