import type { ExecutionContext } from '@nestjs/common';
import type { NestAdapterType, NestHeaderRecord, NestLoggerContext } from '../../types/frameworks/nestjs';
export declare function resolveNestAdapterType(request: unknown, response: unknown): NestAdapterType;
export declare function getNestRequestMethod(request: unknown): string;
export declare function getNestRequestHeaders(request: unknown): NestHeaderRecord | undefined;
export declare function getNestRequestUrl(request: unknown): string;
export declare function getNestRequestPath(request: unknown): string;
export declare function readNestRequestBody(request: unknown): Promise<unknown>;
export declare function setNestRequestStartTime(request: unknown, startTime: number): void;
export declare function getNestRequestStartTime(request: unknown): number | undefined;
export declare function setNestStructuredLogEmitted(request: unknown, emitted: boolean): void;
export declare function getNestStructuredLogEmitted(request: unknown): boolean;
export declare function attachNestRequestLogger(request: unknown, logger: unknown): void;
export declare function buildNestRequestLike(request: unknown): import("../shared").RequestLike;
export declare function getNestResponseStatus(response: unknown): number;
export declare function setNestResponseHeaders(response: unknown, headers: Record<string, string>): void;
export declare function sendNestStatusResponse(response: unknown, statusCode: number): void;
export declare function getControllerName(context: ExecutionContext): string | undefined;
export declare function getHandlerName(context: ExecutionContext): string | undefined;
export declare function createNestLoggerContext(options: {
    request: unknown;
    response: unknown;
    executionContext?: ExecutionContext;
    error?: unknown;
}): NestLoggerContext;
